KeyTopicMap = {
    'dp':'Dynamic Programming',
    'memo':'Dynamic Programming',
    'dfs':'Graphs',
    'bfs':'Graphs',
    'lis':'Dynamic Programming',
    'fft':'fft',
    'ntt':'ntt',
    'fwht':'fwht',
    'gauss':'Gauss',
    'pt':'Geometry',
    'point':'Geometry',
    'circle':'Geometry',
    'line':'Geometry',
    'segment':'Geometry',
    'eps':'Geometry',
    'sieve': 'Number Theory',
    'egcd': 'EGCD',
    'lca': 'Trees',
    'hld': 'HLD',
    'centroid': 'Centroid',
    'matrix': 'Matrix',
    'berlekampmassey': 'Berlekamp Massey',
    'ncr': 'Combinatorics',
    'crt': 'CRT',
    'phi': 'Number Theory',
    'pollardrho': 'Number Theory',
    'lcm': 'Number Theory',
    'tarjan': 'Connectivety',
    'dijkstra': 'Graphs',
    'dijk': 'Graphs',
    'dij': 'Graphs',
    'spfa': 'Graphs',
    'twosat' : '2 Sat',
    '_2sat' : '2 Sat',
    'sat' : '2 Sat',
    'prufer_code': 'Purfer code',
    'prufercode': 'Purfer code',
    'hungarian': 'Hungarian',
    'matching': 'Matching',
    'khun': 'Matching',
    'hopcroftkarp': 'Matching',
    'match': 'Matching',
    'ST': 'Data structure',
    'query': 'Data Structure',
    'upd': 'Data Structure',
    'update': 'Data Structure',
    'trie': 'Trie',
    'insert': 'Data Structure',
    'treap': 'Treap',
    'kmp': 'Strings',
    'zalgo': 'Strings',
    'z_function': 'Strings',
    'AC': 'Aho Corasick',
    'ACA': 'Aho Corasic',
    'suffixarray': 'Suffix Array',
    'suffix_array': 'Suffix Array',
    'lcp': 'Suffix Array',
    'suffixautomaton': 'Suffix Automton',
    'suffix_automaton': 'Suffix Automton',
    'palindromictree': 'Palindromic Tree',
    'eertree': 'Palindromic Tree',
    'cht': 'Convex Hull Trick',
    'linecontainer': 'Convex Hull Trick',
    'lichaotree': 'Li Chao',
    'bitset': 'Bitset',
}